name: Build NodeJS Flavours

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * 2" # 2pm Patch Tuesday

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  node-flavours-build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yarn:
          - latest
          - "1.22.21"
          - "1.22.20"
          - "1.22.0"
          - "1.21.0"
          - "1.20.0"
        node:
          - latest
          - "16.13.0"
          - "16.20.2"
          - "17.9.1"
          - "18.19.0"
          - "19.9.0"
          - "20.9.0"
          - "21.6.1"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2

      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        name: Build & Push
        with:
          context: .
          file: node/Dockerfile
          target: nodejs
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            gone/node:${{ matrix.node }}-${{ matrix.yarn }}
            benzine/node:${{ matrix.node }}-${{ matrix.yarn }}
            ghcr.io/benzine-framework/node:${{ matrix.node }}-${{ matrix.yarn }}
          build-args: |
            NODE_VERSION=${{ matrix.node }}
            YARN_VERSION=${{ matrix.yarn }}
          build-contexts: |
            marshall:build=docker-image://ghcr.io/benzine-framework/marshall:focal
